from django.urls import path

from . import views

urlpatterns = [
    path("studies/", views.study_session_list, name="study_session_list"),
    path(
        "studies/lessons/manage/",
        views.bible_study_lesson_manage_list,
        name="bible_study_lesson_manage_list",
    ),
    path(
        "studies/lessons/new/",
        views.create_bible_study_lesson,
        name="create_bible_study_lesson",
    ),
    path(
        "studies/lessons/<int:lesson_id>/",
        views.bible_study_lesson_detail,
        name="bible_study_lesson_detail",
    ),
    path(
        "studies/lessons/<int:lesson_id>/edit/",
        views.edit_bible_study_lesson,
        name="edit_bible_study_lesson",
    ),
    path(
        "studies/lessons/<int:lesson_id>/cancel/",
        views.cancel_bible_study_lesson,
        name="cancel_bible_study_lesson",
    ),
    path(
        "studies/meetings/manage/",
        views.bible_study_meeting_manage_list,
        name="bible_study_meeting_manage_list",
    ),
    path(
        "studies/meetings/new/",
        views.create_bible_study_meeting,
        name="create_bible_study_meeting",
    ),
    path(
        "studies/meetings/<int:meeting_id>/prepare/",
        views.edit_bible_study_meeting_preparation,
        name="edit_bible_study_meeting_preparation",
    ),
    path(
        "studies/meetings/<int:meeting_id>/worship/",
        views.manage_bible_study_meeting_worship_songs,
        name="manage_bible_study_meeting_worship_songs",
    ),
    path(
        "studies/meetings/<int:meeting_id>/",
        views.bible_study_meeting_detail,
        name="bible_study_meeting_detail",
    ),
    path(
        "studies/meetings/<int:meeting_id>/edit/",
        views.edit_bible_study_meeting,
        name="edit_bible_study_meeting",
    ),
    path(
        "studies/meetings/<int:meeting_id>/cancel/",
        views.cancel_bible_study_meeting,
        name="cancel_bible_study_meeting",
    ),
    path(
        "studies/meetings/worship-songs/<int:song_id>/edit/",
        views.edit_bible_study_meeting_worship_song,
        name="edit_bible_study_meeting_worship_song",
    ),
    path(
        "studies/meetings/worship-songs/<int:song_id>/delete/",
        views.delete_bible_study_meeting_worship_song,
        name="delete_bible_study_meeting_worship_song",
    ),
    path("studies/new/", views.create_study_session, name="create_study_session"),
    path(
        "studies/<int:session_id>/",
        views.study_session_detail,
        name="study_session_detail",
    ),
    path(
        "studies/<int:session_id>/edit/",
        views.edit_study_session,
        name="edit_study_session",
    ),
    path(
        "studies/<int:session_id>/delete/",
        views.delete_study_session,
        name="delete_study_session",
    ),
    path(
        "studies/<int:session_id>/worship/",
        views.manage_worship_songs,
        name="manage_worship_songs",
    ),
    path(
        "studies/worship-songs/<int:song_id>/edit/",
        views.edit_worship_song,
        name="edit_worship_song",
    ),
    path(
        "studies/worship-songs/<int:song_id>/delete/",
        views.delete_worship_song,
        name="delete_worship_song",
    ),
]
