from django.urls import path

from . import views

urlpatterns = [
    path("studies/", views.study_session_list, name="study_session_list"),
    path(
        "studies/schedules/manage/",
        views.bible_study_schedule_manage_list,
        name="bible_study_schedule_manage_list",
    ),
    path(
        "studies/schedules/new/",
        views.create_bible_study_schedule,
        name="create_bible_study_schedule",
    ),
    path(
        "studies/schedules/<int:series_id>/",
        views.bible_study_schedule_detail,
        name="bible_study_schedule_detail",
    ),
    path(
        "studies/schedules/<int:series_id>/edit/",
        views.edit_bible_study_schedule,
        name="edit_bible_study_schedule",
    ),
    path(
        "studies/lessons/manage/",
        views.bible_study_lesson_manage_list,
        name="bible_study_lesson_manage_list",
    ),
    path(
        "studies/lessons/new/",
        views.create_bible_study_lesson,
        name="create_bible_study_lesson",
    ),
    path(
        "studies/lessons/<int:lesson_id>/",
        views.bible_study_lesson_detail,
        name="bible_study_lesson_detail",
    ),
    path(
        "studies/lessons/<int:lesson_id>/edit/",
        views.edit_bible_study_lesson,
        name="edit_bible_study_lesson",
    ),
    path(
        "studies/lessons/<int:lesson_id>/generate-meetings/",
        views.generate_bible_study_meetings,
        name="generate_bible_study_meetings",
    ),
    path(
        "studies/lessons/<int:lesson_id>/cancel/",
        views.cancel_bible_study_lesson,
        name="cancel_bible_study_lesson",
    ),
    path(
        "studies/meetings/manage/",
        views.bible_study_meeting_manage_list,
        name="bible_study_meeting_manage_list",
    ),
    path(
        "studies/meetings/new/",
        views.create_bible_study_meeting,
        name="create_bible_study_meeting",
    ),
    path(
        "studies/meetings/<int:meeting_id>/prepare/",
        views.edit_bible_study_meeting_preparation,
        name="edit_bible_study_meeting_preparation",
    ),
    path(
        "studies/meetings/<int:meeting_id>/roles/",
        views.manage_bible_study_meeting_roles,
        name="manage_bible_study_meeting_roles",
    ),
    path(
        "studies/meetings/<int:meeting_id>/worship/",
        views.manage_bible_study_meeting_worship_songs,
        name="manage_bible_study_meeting_worship_songs",
    ),
    path(
        "studies/meetings/<int:meeting_id>/",
        views.bible_study_meeting_detail,
        name="bible_study_meeting_detail",
    ),
    path(
        "studies/meetings/<int:meeting_id>/edit/",
        views.edit_bible_study_meeting,
        name="edit_bible_study_meeting",
    ),
    path(
        "studies/meetings/<int:meeting_id>/cancel/",
        views.cancel_bible_study_meeting,
        name="cancel_bible_study_meeting",
    ),
    path(
        "studies/meetings/roles/<int:role_id>/edit/",
        views.edit_bible_study_meeting_role,
        name="edit_bible_study_meeting_role",
    ),
    path(
        "studies/meetings/roles/<int:role_id>/delete/",
        views.delete_bible_study_meeting_role,
        name="delete_bible_study_meeting_role",
    ),
    path(
        "studies/meetings/worship-songs/<int:song_id>/edit/",
        views.edit_bible_study_meeting_worship_song,
        name="edit_bible_study_meeting_worship_song",
    ),
    path(
        "studies/meetings/worship-songs/<int:song_id>/delete/",
        views.delete_bible_study_meeting_worship_song,
        name="delete_bible_study_meeting_worship_song",
    ),
]
