UI_TEXT = {
    "zh": {
        "site_title": "教会生活",
        "today": "今日",
        "my_plans": "读经",
        "group_progress": "小组进度",
        "admin": "后台",
        "login": "登录",
        "logout": "退出",
        "create_account": "创建账号",
        "hi": "你好",
        "language": "语言",

        "today_subtitle": "今天的读经、查经、代祷和服事提醒。",
        "available_plans": "可加入的读经计划",
        "available_plans_subtitle": "加入一个计划，开始和小组一起读经。",
        "join_this_plan": "加入这个计划",
        "view_plan": "查看计划",
        "view_my_reading_plans": "查看我的读经计划",
        "back_to_today": "返回今日",
        "my_reading_plans": "我的读经计划",
        "status_label": "状态",
        "starts_on": "开始日期",
        "in_progress": "进行中",
        "leave_plan": "退出计划",

        "not_started": "尚未开始",
        "ended": "已结束",
        "rest_day": "休息 / 补读日",
        "checked_in": "已打卡",
        "not_checked_in": "未打卡",
        "progress": "进度",
        "reading_days": "读经日",
        "today_reading": "今日经文",
        "start_reading": "开始读经",
        "start_today_reading": "开始今日读经",
        "memory_verse": "背诵经文",
        "reflection_checkin_note": "默想分享和打卡在经文阅读器最后。",
        "no_available_plans": "目前没有可加入的读经计划。",
        "no_reading_plan_yet": "你还没有加入读经计划。",
        "join_plan_to_start": "从下面选择一个读经计划开始。",
        "no_active_reading_plan": "你目前没有进行中的读经计划。",
        "browse_reading_plans": "浏览读经计划",
        "no_scripture_links": "无法为这段读经内容生成经文链接。",
        "no_memory_link": "无法为背诵经文生成链接。",

        "scripture_reader": "经文阅读",
        "reading": "读经",
        "chinese": "中文",
        "english": "English",
        "open_scripture_directly": "如果嵌入页面无法加载，请直接打开经文。",
        "audio": "音频",
        "open_audio": "打开音频",
        "audio_note": "音频按整章播放，节选经文可能仍会播放整章。",
        "reflection": "默想分享",
        "reflection_optional": "读完后可以分享默想，分享不是打卡的前置条件。",
        "post_reflection": "发表默想",
        "reply": "回复",
        "delete": "删除",
        "no_reflections": "还没有默想分享。",
        "finish_today_reading": "完成今日读经",
        "finished_reading_button": "我已完成今日读经",
        "future_checkin_unavailable": "这一天还不能打卡。",
        "continue_reading": "继续读经",
        "continue_next_passage": "继续下一段经文",
        "back_to_plan": "返回计划",
        "previous_passage": "上一段",
        "next_passage": "下一段",

        "username": "用户名",
        "email_optional": "Email（可选）",
        "small_group": "小组",
        "password": "密码",
        "password_confirmation": "确认密码",
        "no_small_group": "暂不选择小组",
        "new_here": "第一次来？",
        "already_have_account": "已经有账号？",
        "profile": "个人资料",
        "account_profile": "账号资料",
        "profile_subtitle": "更新你的 email、小组和语言偏好。",
        "username_readonly": "用户名不可修改",
        "save_profile": "保存资料",
        "profile_saved": "个人资料已保存。",
        "email": "Email",
        "preferred_language": "语言偏好",
        "change_password": "修改密码",
        "password_change_done": "密码已修改",
        "password_change_done_message": "你的密码已经成功更新。",
        "back_to_profile": "返回个人资料",
        "visibility": "可见范围",
        "private_reflection": "私人默想",
        "group_reflection": "我的小组",
        "church_reflection": "默想墙",
        "post_anonymously": "匿名发布",
        "view_passage_wall": "查看默想墙",

        "reading_plan_admin": "读经计划管理",
        "reading_plan_admin_subtitle": "分别编辑读经计划标题和每日读经内容。",
        "back_to_django_admin": "返回 Django 管理后台",
        "plan": "计划",
        "english_name": "英文名称",
        "status": "状态",
        "header": "标题",
        "days": "每日内容",
        "edit_header": "编辑标题",
        "edit_days": "编辑每日内容",
        "active": "启用",
        "inactive": "停用",
        "no_reading_plans_found": "没有找到读经计划。",

        "user_admin": "用户管理",
        "user_admin_subtitle": "搜索用户，并为无法使用邮件找回密码的成员重置密码。",
        "search": "搜索",
        "admin_email": "邮箱",
        "admin_small_group": "小组",
        "password_status": "密码状态",
        "action": "操作",
        "reset_password": "重置密码",
        "ok": "正常",
        "must_change_password": "需要修改密码",
        "user_search_placeholder": "用户名、邮箱或小组",
        "no_users_found": "没有找到用户。",

        "reflection_reports": "默想举报",
        "reflection_reports_subtitle": "查看被举报的默想并管理可见性。",
        "filter": "筛选",
        "open": "未处理",
        "reviewed": "已处理",
        "dismissed": "已忽略",
        "author": "作者",
        "hidden": "已隐藏",
        "reported_by": "举报人",
        "reason": "原因",
        "hidden_reason": "隐藏原因",
        "hide_reason": "隐藏原因",
        "reason_shown_internally": "仅内部可见的处理原因",
        "hide_reflection": "隐藏默想",
        "unhide_reflection": "取消隐藏默想",
        "mark_reports_reviewed": "标记举报已处理",
        "dismiss_reports": "忽略举报",
        "report_search_placeholder": "作者、举报人、经文、原因或内容",
        "no_reports_found": "没有找到举报。",
    },
    "en": {
        "site_title": "Church Life",
        "today": "Today",
        "my_plans": "Reading",
        "group_progress": "Group Progress",
        "admin": "Admin",
        "login": "Login",
        "logout": "Logout",
        "create_account": "Create Account",
        "hi": "Hi",
        "language": "Language",

        "today_subtitle": "Today's reading, Bible study, prayer, and serving reminders.",
        "available_plans": "Available Reading Plans",
        "available_plans_subtitle": "Join a plan to begin reading with your group.",
        "join_this_plan": "Join this plan",
        "view_plan": "View Plan",
        "view_my_reading_plans": "View my reading plans",
        "back_to_today": "Back to Today",
        "my_reading_plans": "My Reading Plans",
        "status_label": "Status",
        "starts_on": "Starts on",
        "in_progress": "In progress",
        "leave_plan": "Leave Plan",

        "not_started": "Not started",
        "ended": "Ended",
        "rest_day": "Rest / Catch-up Day",
        "checked_in": "Checked in",
        "not_checked_in": "Not checked in",
        "progress": "Progress",
        "reading_days": "reading days",
        "today_reading": "Today's Reading",
        "start_reading": "Start Reading",
        "start_today_reading": "Start Today’s Reading",
        "memory_verse": "Memory Verse",
        "reflection_checkin_note": "Reflection and check-in are available at the end of the Scripture Reader.",
        "no_available_plans": "No available reading plans right now.",
        "no_reading_plan_yet": "You have not joined any reading plan yet.",
        "join_plan_to_start": "Join an available reading plan below to start.",
        "no_active_reading_plan": "You do not have an active reading plan right now.",
        "browse_reading_plans": "Browse reading plans",
        "no_scripture_links": "No scripture links could be generated for this reading text.",
        "no_memory_link": "No memory verse link could be generated.",

        "scripture_reader": "Scripture Reader",
        "reading": "Reading",
        "chinese": "中文",
        "english": "English",
        "open_scripture_directly": "If the embedded page does not load, open scripture directly.",
        "audio": "Audio",
        "open_audio": "Open audio",
        "audio_note": "Audio is chapter-based. Verse ranges may still play the full chapter.",
        "reflection": "Reflection",
        "reflection_optional": "You may share a reflection after reading. This is optional.",
        "post_reflection": "Post reflection",
        "reply": "Reply",
        "delete": "Delete",
        "no_reflections": "No reflections yet.",
        "finish_today_reading": "Finish Today’s Reading",
        "finished_reading_button": "I finished today’s reading",
        "future_checkin_unavailable": "This reading day is not available for check-in yet.",
        "continue_reading": "Continue Reading",
        "continue_next_passage": "Continue to Next Passage",
        "back_to_plan": "Back to Plan",
        "previous_passage": "Previous Passage",
        "next_passage": "Next Passage",

        "username": "Username",
        "email_optional": "Email (optional)",
        "small_group": "Small group",
        "password": "Password",
        "password_confirmation": "Password confirmation",
        "no_small_group": "No small group yet",
        "new_here": "New here?",
        "already_have_account": "Already have an account?",
        "profile": "Profile",
        "account_profile": "Account Profile",
        "profile_subtitle": "Update your email, small group, and language preference.",
        "username_readonly": "Username cannot be changed",
        "save_profile": "Save Profile",
        "profile_saved": "Profile saved.",
        "email": "Email",
        "preferred_language": "Language preference",
        "change_password": "Change Password",
        "password_change_done": "Password Changed",
        "password_change_done_message": "Your password has been updated successfully.",
        "back_to_profile": "Back to Profile",
        "visibility": "Visibility",
        "private_reflection": "Private",
        "group_reflection": "My Group",
        "church_reflection": "Reflection Wall",
        "post_anonymously": "Post anonymously",
        "view_passage_wall": "View Reflection Wall",

        "reading_plan_admin": "Reading Plan Admin",
        "reading_plan_admin_subtitle": "Edit reading plan headers and reading days separately.",
        "back_to_django_admin": "Back to Django Admin",
        "plan": "Plan",
        "english_name": "English Name",
        "status": "Status",
        "header": "Header",
        "days": "Days",
        "edit_header": "Edit Header",
        "edit_days": "Edit Days",
        "active": "Active",
        "inactive": "Inactive",
        "no_reading_plans_found": "No reading plans found.",

        "user_admin": "User Admin",
        "user_admin_subtitle": "Search users and reset passwords for members who cannot use email recovery.",
        "search": "Search",
        "admin_email": "Email",
        "admin_small_group": "Small Group",
        "password_status": "Password Status",
        "action": "Action",
        "reset_password": "Reset Password",
        "ok": "OK",
        "must_change_password": "Must change password",
        "user_search_placeholder": "Username, email, or small group",
        "no_users_found": "No users found.",

        "reflection_reports": "Reflection Reports",
        "reflection_reports_subtitle": "Review reported reflections and moderate visibility.",
        "filter": "Filter",
        "open": "Open",
        "reviewed": "Reviewed",
        "dismissed": "Dismissed",
        "author": "Author",
        "hidden": "Hidden",
        "reported_by": "Reported by",
        "reason": "Reason",
        "hidden_reason": "Hidden reason",
        "hide_reason": "Hide reason",
        "reason_shown_internally": "Reason shown internally",
        "hide_reflection": "Hide Reflection",
        "unhide_reflection": "Unhide Reflection",
        "mark_reports_reviewed": "Mark Reports Reviewed",
        "dismiss_reports": "Dismiss Reports",
        "report_search_placeholder": "Author, reporter, scripture, reason, or content",
        "no_reports_found": "No reports found.",
    },
}
