UI_TEXT = {
    "zh": {
        "site_title": "教会生活",
        "today": "今日",
        "my_plans": "读经",
        "group_progress": "小组进度",
        "admin": "后台",
        "login": "登录",
        "logout": "退出",
        "create_account": "创建账号",
        "hi": "你好",
        "language": "语言",

        "today_subtitle": "今天的读经、查经、代祷和服事提醒。",
        "available_plans": "可加入的读经计划",
        "available_plans_subtitle": "加入一个计划，开始和小组一起读经。",
        "join_this_plan": "加入这个计划",
        "view_plan": "查看计划",
        "view_my_reading_plans": "查看我的读经计划",
        "back_to_today": "返回今日",
        "my_reading_plans": "我的读经计划",
        "status_label": "状态",
        "starts_on": "开始日期",
        "in_progress": "进行中",
        "leave_plan": "退出计划",

        "not_started": "尚未开始",
        "ended": "已结束",
        "rest_day": "休息 / 补读日",
        "checked_in": "已打卡",
        "not_checked_in": "未打卡",
        "progress": "进度",
        "reading_days": "读经日",
        "today_reading": "今日经文",
        "start_reading": "开始读经",
        "start_today_reading": "开始今日读经",
        "memory_verse": "背诵经文",
        "reflection_checkin_note": "默想分享和打卡在经文阅读器最后。",
        "no_available_plans": "目前没有可加入的读经计划。",
        "no_reading_plan_yet": "你还没有加入读经计划。",
        "join_plan_to_start": "从下面选择一个读经计划开始。",
        "no_active_reading_plan": "你目前没有进行中的读经计划。",
        "browse_reading_plans": "浏览读经计划",
        "no_scripture_links": "无法为这段读经内容生成经文链接。",
        "no_memory_link": "无法为背诵经文生成链接。",

        "scripture_reader": "经文阅读",
        "reading": "读经",
        "chinese": "中文",
        "english": "English",
        "open_scripture_directly": "如果嵌入页面无法加载，请直接打开经文。",
        "audio": "音频",
        "open_audio": "打开音频",
        "audio_note": "音频按整章播放，节选经文可能仍会播放整章。",
        "reflection": "默想分享",
        "reflection_optional": "读完后可以分享默想，分享不是打卡的前置条件。",
        "post_reflection": "发表默想",
        "reply": "回复",
        "delete": "删除",
        "no_reflections": "还没有默想分享。",
        "finish_today_reading": "完成今日读经",
        "finished_reading_button": "我已完成今日读经",
        "future_checkin_unavailable": "这一天还不能打卡。",
        "continue_reading": "继续读经",
        "continue_next_passage": "继续下一段经文",
        "back_to_plan": "返回计划",
        "previous_passage": "上一段",
        "next_passage": "下一段",

        "username": "用户名",
        "email_optional": "Email（可选）",
        "small_group": "小组",
        "password": "密码",
        "password_confirmation": "确认密码",
        "no_small_group": "不确定 / 新朋友",
        "new_here": "第一次来？",
        "already_have_account": "已经有账号？",
        "profile": "个人资料",
        "account_profile": "账号资料",
        "profile_subtitle": "更新你的 email、语言偏好，或请同工协助确认你参加的小组。",
        "username_readonly": "用户名不可修改",
        "save_profile": "保存资料",
        "profile_saved": "个人资料已保存。",
        "profile_saved_with_group_request": "个人资料已保存。你的小组申请已提交，请等待同工确认。",
        "account_created": "账号已创建。",
        "account_created_with_group_request": "账号已创建。你的小组申请已提交，请等待同工确认。",
        "email": "Email",
        "preferred_language": "语言偏好",
        "your_small_group": "我参加的小组",
        "current_confirmed_small_group": "目前确认的小组",
        "pending_group_request": "等待确认的小组申请",
        "pending_group_request_help": "同工确认后，你的小组相关内容会自动更新。",
        "requested_small_group_help": "如果你已经参加小组，请选择小组名称；如果不确定，可以先选择“不确定 / 新朋友”。",
        "profile_requested_small_group_help": "需要更改小组时请选择新的小组；同工确认前，你目前的小组不会改变。",
        "change_password": "修改密码",
        "password_change_done": "密码已修改",
        "password_change_done_message": "你的密码已经成功更新。",
        "back_to_profile": "返回个人资料",
        "visibility": "可见范围",
        "private_reflection": "私人默想",
        "group_reflection": "我的小组",
        "church_reflection": "默想墙",
        "post_anonymously": "匿名发布",
        "view_passage_wall": "查看默想墙",

        "reading_plan_admin": "读经计划管理",
        "reading_plan_admin_subtitle": "分别编辑读经计划标题和每日读经内容。",
        "back_to_django_admin": "返回 Django 管理后台",
        "plan": "计划",
        "english_name": "英文名称",
        "status": "状态",
        "header": "标题",
        "days": "每日内容",
        "edit_header": "编辑标题",
        "edit_days": "编辑每日内容",
        "active": "启用",
        "inactive": "停用",
        "no_reading_plans_found": "没有找到读经计划。",

        "user_admin": "用户管理",
        "user_admin_subtitle": "搜索用户，并为无法使用邮件找回密码的成员重置密码。",
        "search": "搜索",
        "admin_email": "邮箱",
        "admin_small_group": "小组",
        "password_status": "密码状态",
        "action": "操作",
        "reset_password": "重置密码",
        "ok": "正常",
        "must_change_password": "需要修改密码",
        "user_search_placeholder": "用户名、邮箱或小组",
        "no_users_found": "没有找到用户。",
        "membership_requests": "小组申请审核",
        "membership_requests_subtitle": "审核待确认的小组/团契申请；目前生效的小组资料仍会决定相关内容范围。",
        "pending_review_queue": "等待审核队列",
        "pending_review_queue_help": "此列表只显示现有状态为“等待审核”的申请。",
        "pending_review_count": "等待审核",
        "staff_membership_empty_title": "目前没有等待审核的申请",
        "staff_membership_empty_body": "新的注册或资料更新申请会出现在这里；空队列不会改变目前生效的小组资料。",
        "requested_small_group": "我参加的小组",
        "requested_unit": "申请加入的小组/团契",
        "requested_by": "申请人",
        "request_source": "申请来源",
        "submitted": "提交时间",
        "current_small_group": "当前小组",
        "future_foundation_membership": "归属记录",
        "future_foundation_membership_request": "申请加入的小组/团契",
        "current_runtime_small_group": "当前小组",
        "current_runtime_context": "目前生效的小组资料",
        "future_foundation_context": "确认后的归属记录",
        "approval_state": "审核状态",
        "approval_state_help": "确认后会建立主要归属记录；只有当申请的小组正好对应一个启用中的当前小组时，才会更新目前生效的小组资料。",
        "legacy_sync_target": "确认后会更新到的小组",
        "no_legacy_sync_target": "没有唯一启用中的当前小组",
        "pending_review": "等待审核",
        "request_note": "申请备注",
        "notes_must_be_non_sensitive": "备注必须只包含非敏感的操作信息。",
        "no_membership_requests_found": "目前没有需要审核的小组/团契申请。",
        "membership_request_detail": "小组申请详情",
        "existing_active_primary_membership": "现有已确认归属",
        "no_active_primary_membership": "没有现有已确认归属",
        "approve_request": "确认申请并按规则同步",
        "reject_request": "不通过申请",
        "back_to_membership_requests": "返回小组申请审核",
        "profile_small_group_sync_warning": (
            "提醒：确认后会把目前生效的小组资料更新为这个小组，"
            "可能影响现有内容范围："
        ),

        "moderation_queue": "内容审核队列",
        "moderation_queue_subtitle": "只读汇总；请进入现有举报审核流程处理具体事项。",
        "moderation_queue_boundary": "此页面只汇总现有举报与隐藏状态，不新增处理状态、备注或操作。",
        "reported_prayer_requests": "被举报的代祷事项",
        "reported_prayer_comments": "被举报的代祷评论",
        "hidden_prayer_requests": "已隐藏代祷事项",
        "hidden_prayer_comments": "已隐藏代祷评论",
        "reported_reflection_posts": "被举报的默想",
        "reported_reflection_replies": "被举报的默想回复",
        "hidden_reflection_posts": "已隐藏默想",
        "hidden_reflection_replies": "已隐藏默想回复",
        "open_existing_workflow": "进入现有审核流程",
        "view_prayer": "查看代祷事项",
        "not_tracked_existing_data": "现有资料没有单独记录此类别的举报或隐藏状态。",
        "no_items_in_queue": "此队列目前没有项目。",
        "latest_items": "最近项目",
        "review_queue": "审核队列",
        "ministry_ops_health": "事工运作提醒指标",
        "inactive_ministry_teams": "停用的事工团队",
        "teams_missing_playbook": "缺少服事手册链接的团队",
        "display_name_only_members": "仅显示名称的服事人员",
        "teams_without_active_members": "没有启用成员的团队",
        "assignments_without_active_members": "没有启用成员的将来排班",
        "assignments_with_inactive_team": "使用停用团队的将来排班",
        "no_ministry_ops_issues": "目前没有可由现有资料看出的事工设置提醒指标。",
        "review_team_setup": "检查团队设置",
        "reflection_reports": "默想举报",
        "reflection_reports_subtitle": "查看被举报的默想并管理可见性。",
        "filter": "筛选",
        "open": "未处理",
        "reviewed": "已处理",
        "dismissed": "已忽略",
        "author": "作者",
        "hidden": "已隐藏",
        "reported_by": "举报人",
        "reason": "原因",
        "hidden_reason": "隐藏原因",
        "hide_reason": "隐藏原因",
        "reason_shown_internally": "仅内部可见的处理原因",
        "hide_reflection": "隐藏默想",
        "unhide_reflection": "取消隐藏默想",
        "mark_reports_reviewed": "标记举报已处理",
        "dismiss_reports": "忽略举报",
        "report_search_placeholder": "作者、举报人、经文、原因或内容",
        "no_reports_found": "没有找到举报。",
    },
    "en": {
        "site_title": "Church Life",
        "today": "Today",
        "my_plans": "Reading",
        "group_progress": "Group Progress",
        "admin": "Admin",
        "login": "Login",
        "logout": "Logout",
        "create_account": "Create Account",
        "hi": "Hi",
        "language": "Language",

        "today_subtitle": "Today's reading, Bible study, prayer, and serving reminders.",
        "available_plans": "Available Reading Plans",
        "available_plans_subtitle": "Join a plan to begin reading with your group.",
        "join_this_plan": "Join this plan",
        "view_plan": "View Plan",
        "view_my_reading_plans": "View my reading plans",
        "back_to_today": "Back to Today",
        "my_reading_plans": "My Reading Plans",
        "status_label": "Status",
        "starts_on": "Starts on",
        "in_progress": "In progress",
        "leave_plan": "Leave Plan",

        "not_started": "Not started",
        "ended": "Ended",
        "rest_day": "Rest / Catch-up Day",
        "checked_in": "Checked in",
        "not_checked_in": "Not checked in",
        "progress": "Progress",
        "reading_days": "reading days",
        "today_reading": "Today's Reading",
        "start_reading": "Start Reading",
        "start_today_reading": "Start Today’s Reading",
        "memory_verse": "Memory Verse",
        "reflection_checkin_note": "Reflection and check-in are available at the end of the Scripture Reader.",
        "no_available_plans": "No available reading plans right now.",
        "no_reading_plan_yet": "You have not joined any reading plan yet.",
        "join_plan_to_start": "Join an available reading plan below to start.",
        "no_active_reading_plan": "You do not have an active reading plan right now.",
        "browse_reading_plans": "Browse reading plans",
        "no_scripture_links": "No scripture links could be generated for this reading text.",
        "no_memory_link": "No memory verse link could be generated.",

        "scripture_reader": "Scripture Reader",
        "reading": "Reading",
        "chinese": "中文",
        "english": "English",
        "open_scripture_directly": "If the embedded page does not load, open scripture directly.",
        "audio": "Audio",
        "open_audio": "Open audio",
        "audio_note": "Audio is chapter-based. Verse ranges may still play the full chapter.",
        "reflection": "Reflection",
        "reflection_optional": "You may share a reflection after reading. This is optional.",
        "post_reflection": "Post reflection",
        "reply": "Reply",
        "delete": "Delete",
        "no_reflections": "No reflections yet.",
        "finish_today_reading": "Finish Today’s Reading",
        "finished_reading_button": "I finished today’s reading",
        "future_checkin_unavailable": "This reading day is not available for check-in yet.",
        "continue_reading": "Continue Reading",
        "continue_next_passage": "Continue to Next Passage",
        "back_to_plan": "Back to Plan",
        "previous_passage": "Previous Passage",
        "next_passage": "Next Passage",

        "username": "Username",
        "email_optional": "Email (optional)",
        "small_group": "Small group",
        "password": "Password",
        "password_confirmation": "Password confirmation",
        "no_small_group": "Not sure / new here",
        "new_here": "New here?",
        "already_have_account": "Already have an account?",
        "profile": "Profile",
        "account_profile": "Account Profile",
        "profile_subtitle": "Update your email, language preference, or ask staff to confirm your group.",
        "username_readonly": "Username cannot be changed",
        "save_profile": "Save Profile",
        "profile_saved": "Profile saved.",
        "profile_saved_with_group_request": "Profile saved. Your group request was sent for staff confirmation.",
        "account_created": "Your account has been created.",
        "account_created_with_group_request": "Your account has been created. Your group request was sent for staff confirmation.",
        "email": "Email",
        "preferred_language": "Language preference",
        "your_small_group": "Your small group",
        "current_confirmed_small_group": "Current confirmed group",
        "pending_group_request": "Group request waiting for confirmation",
        "pending_group_request_help": "After staff confirm it, your group-related content will update automatically.",
        "requested_small_group_help": "Choose your group if you already attend one. If you are not sure, leave this as “Not sure / new here.”",
        "profile_requested_small_group_help": "Choose a new group when you need an update. Your current group will not change until staff confirm it.",
        "change_password": "Change Password",
        "password_change_done": "Password Changed",
        "password_change_done_message": "Your password has been updated successfully.",
        "back_to_profile": "Back to Profile",
        "visibility": "Visibility",
        "private_reflection": "Private",
        "group_reflection": "My Group",
        "church_reflection": "Reflection Wall",
        "post_anonymously": "Post anonymously",
        "view_passage_wall": "View Reflection Wall",

        "reading_plan_admin": "Reading Plan Admin",
        "reading_plan_admin_subtitle": "Edit reading plan headers and reading days separately.",
        "back_to_django_admin": "Back to Django Admin",
        "plan": "Plan",
        "english_name": "English Name",
        "status": "Status",
        "header": "Header",
        "days": "Days",
        "edit_header": "Edit Header",
        "edit_days": "Edit Days",
        "active": "Active",
        "inactive": "Inactive",
        "no_reading_plans_found": "No reading plans found.",

        "user_admin": "User Admin",
        "user_admin_subtitle": "Search users and reset passwords for members who cannot use email recovery.",
        "search": "Search",
        "admin_email": "Email",
        "admin_small_group": "Small Group",
        "password_status": "Password Status",
        "action": "Action",
        "reset_password": "Reset Password",
        "ok": "OK",
        "must_change_password": "Must change password",
        "user_search_placeholder": "Username, email, or small group",
        "no_users_found": "No users found.",
        "membership_requests": "Group Requests",
        "membership_requests_subtitle": "Review pending group/fellowship requests. Current access still follows the current active group data.",
        "pending_review_queue": "Pending review queue",
        "pending_review_queue_help": "This list only shows requests whose existing status is pending review.",
        "pending_review_count": "Pending review",
        "staff_membership_empty_title": "No requests are waiting for review",
        "staff_membership_empty_body": "New signup or profile-update requests will appear here. An empty queue does not change the current active group data.",
        "requested_small_group": "Your small group",
        "requested_unit": "Requested group/fellowship",
        "requested_by": "Requested By",
        "request_source": "Request Source",
        "submitted": "Submitted",
        "current_small_group": "Current small group",
        "future_foundation_membership": "Group membership",
        "future_foundation_membership_request": "Requested group/fellowship",
        "current_runtime_small_group": "Current small group",
        "current_runtime_context": "Current active group data",
        "future_foundation_context": "Group membership after approval",
        "approval_state": "Approval state",
        "approval_state_help": "Approval creates the primary membership record. The current active small group updates only when the requested group maps to exactly one active current small group.",
        "legacy_sync_target": "Current group update target",
        "no_legacy_sync_target": "No single active current small group",
        "pending_review": "Pending review",
        "request_note": "Request Note",
        "notes_must_be_non_sensitive": "Notes must contain only non-sensitive operational information.",
        "no_membership_requests_found": "No group or fellowship requests need review right now.",
        "membership_request_detail": "Group Request Detail",
        "existing_active_primary_membership": "Existing confirmed membership",
        "no_active_primary_membership": "No existing confirmed membership",
        "approve_request": "Confirm and Sync by Rule",
        "reject_request": "Decline Request",
        "back_to_membership_requests": "Back to Group Requests",
        "profile_small_group_sync_warning": (
            "Warning: confirming this request will update the current active group data "
            "to this group and may affect current content visibility:"
        ),

        "moderation_queue": "Moderation Queue",
        "moderation_queue_subtitle": "Read-only summary; use the existing report review workflows for action.",
        "moderation_queue_boundary": "This page summarizes existing report and hidden states only. It adds no new moderation states, notes, or actions.",
        "reported_prayer_requests": "Reported prayer requests",
        "reported_prayer_comments": "Reported prayer comments",
        "hidden_prayer_requests": "Hidden prayer requests",
        "hidden_prayer_comments": "Hidden prayer comments",
        "reported_reflection_posts": "Reported reflections",
        "reported_reflection_replies": "Reported reflection replies",
        "hidden_reflection_posts": "Hidden reflections",
        "hidden_reflection_replies": "Hidden reflection replies",
        "open_existing_workflow": "Open existing workflow",
        "view_prayer": "View Prayer Request",
        "not_tracked_existing_data": "Existing data does not track separate report or hidden state for this category.",
        "no_items_in_queue": "No items in this queue right now.",
        "latest_items": "Latest items",
        "review_queue": "Review Queue",
        "ministry_ops_health": "Ministry ops health flags",
        "inactive_ministry_teams": "Inactive ministry teams",
        "teams_missing_playbook": "Teams missing playbook links",
        "display_name_only_members": "Display-name-only members",
        "teams_without_active_members": "Teams with no active members",
        "assignments_without_active_members": "Upcoming assignments without active members",
        "assignments_with_inactive_team": "Upcoming assignments using inactive teams",
        "no_ministry_ops_issues": "No ministry setup warning indicators are visible from existing data right now.",
        "review_team_setup": "Review Team Setup",
        "reflection_reports": "Reflection Reports",
        "reflection_reports_subtitle": "Review reported reflections and moderate visibility.",
        "filter": "Filter",
        "open": "Open",
        "reviewed": "Reviewed",
        "dismissed": "Dismissed",
        "author": "Author",
        "hidden": "Hidden",
        "reported_by": "Reported by",
        "reason": "Reason",
        "hidden_reason": "Hidden reason",
        "hide_reason": "Hide reason",
        "reason_shown_internally": "Reason shown internally",
        "hide_reflection": "Hide Reflection",
        "unhide_reflection": "Unhide Reflection",
        "mark_reports_reviewed": "Mark Reports Reviewed",
        "dismiss_reports": "Dismiss Reports",
        "report_search_placeholder": "Author, reporter, scripture, reason, or content",
        "no_reports_found": "No reports found.",
    },
}
