from django.urls import path

from . import views

urlpatterns = [
    path(
        "activities/",
        views.community_activity_list,
        name="community_activity_list",
    ),
    path(
        "activities/new/",
        views.community_activity_create,
        name="community_activity_create",
    ),
    path(
        "activities/review/",
        views.community_activity_review_list,
        name="community_activity_review_list",
    ),
    path(
        "activities/user-search/",
        views.community_activity_user_search,
        name="community_activity_user_search",
    ),
    path(
        "activities/<int:activity_id>/",
        views.community_activity_detail,
        name="community_activity_detail",
    ),
    path(
        "activities/<int:activity_id>/edit/",
        views.community_activity_edit,
        name="community_activity_edit",
    ),
    path(
        "activities/<int:activity_id>/review/",
        views.community_activity_review_detail,
        name="community_activity_review_detail",
    ),
    path(
        "activities/<int:activity_id>/review/publish/",
        views.community_activity_review_publish,
        name="community_activity_review_publish",
    ),
    path(
        "activities/<int:activity_id>/review/request-changes/",
        views.community_activity_review_request_changes,
        name="community_activity_review_request_changes",
    ),
    path(
        "activities/<int:activity_id>/review/cancel/",
        views.community_activity_review_cancel,
        name="community_activity_review_cancel",
    ),
    path(
        "activities/<int:activity_id>/signup/",
        views.community_activity_signup,
        name="community_activity_signup",
    ),
    path(
        "activities/<int:activity_id>/cancel-signup/",
        views.community_activity_cancel_signup,
        name="community_activity_cancel_signup",
    ),
]
