# Generated by Django 5.2.14 on 2026-05-21 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_district_churchroleassignment_smallgroup_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('bible_study', 'Bible Study'), ('special_meeting', 'Special Meeting'), ('conference', 'Conference'), ('gospel_music', 'Gospel Music Night'), ('baptism', 'Baptism'), ('other', 'Other')], max_length=40)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=180)),
                ('meeting_link', models.URLField(blank=True, default='', max_length=500)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('district', 'District'), ('small_group', 'Small Group')], default='global', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_events', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='accounts.district')),
                ('small_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='accounts.smallgroup')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['event_type'], name='events_serv_event_t_9549a1_idx'), models.Index(fields=['status'], name='events_serv_status_44e242_idx'), models.Index(fields=['start_datetime'], name='events_serv_start_d_757774_idx'), models.Index(fields=['scope_type'], name='events_serv_scope_t_edf623_idx')],
            },
        ),
    ]
