# Generated by Django 5.2.14 on 2026-05-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ministrycontext_district_ministry_context'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='ministry_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='accounts.ministrycontext'),
        ),
    ]
