# Generated by Django 5.2.14 on 2026-06-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_serviceevent_ministry_context_and_more'),
        ('ministry', '0002_teamassignment_teamassignmentmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEventRequiredTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_event_links', to='ministry.ministryteam')),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_team_links', to='events.serviceevent')),
            ],
            options={
                'ordering': ['service_event__start_datetime', 'ministry_team__name'],
            },
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='required_teams',
            field=models.ManyToManyField(blank=True, related_name='required_service_events', through='events.ServiceEventRequiredTeam', to='ministry.ministryteam'),
        ),
        migrations.AddIndex(
            model_name='serviceeventrequiredteam',
            index=models.Index(fields=['service_event'], name='events_serv_service_e6ff91_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceeventrequiredteam',
            index=models.Index(fields=['ministry_team'], name='events_serv_ministr_cd94e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceeventrequiredteam',
            constraint=models.UniqueConstraint(fields=('service_event', 'ministry_team'), name='unique_service_event_required_team'),
        ),
    ]
