# Generated by Django 5.2.14 on 2026-06-07 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_serviceeventrequiredteam_serviceevent_required_teams_and_more'),
        ('ministry', '0002_teamassignment_teamassignmentmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='rotation_anchor_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_anchor_service_events', to='ministry.ministryteam'),
        ),
    ]
