# Generated by Django 5.2.14 on 2026-06-07 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_churchstructuremembership'),
        ('events', '0004_serviceevent_rotation_anchor_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEventAudienceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_scope_links', to='events.serviceevent')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_event_audience_scope_links', to='accounts.churchstructureunit')),
            ],
            options={
                'ordering': ['service_event__start_datetime', 'unit__parent_id', 'unit__sort_order', 'unit__code', 'unit__name'],
                'indexes': [models.Index(fields=['service_event'], name='events_serv_service_b8334a_idx'), models.Index(fields=['unit'], name='events_serv_unit_id_60e266_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_event', 'unit'), name='unique_service_event_audience_scope')],
            },
        ),
    ]
