# Generated by Django 5.2.15 on 2026-06-19 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_churchroleassignment_structure_unit_and_more'),
        ('events', '0005_serviceeventaudiencescope'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='host_language_unit',
            field=models.ForeignKey(blank=True, help_text='Display-only Host / Language context. Does not control audience or visibility.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='host_language_service_events', to='accounts.churchstructureunit'),
        ),
    ]
