# Generated by Django 5.2.15 on 2026-06-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_serviceevent_host_language_unit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceevent',
            name='events_serv_scope_t_edf623_idx',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='district',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='scope_type',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='small_group',
        ),
    ]
