# Generated by Django 5.2.15 on 2026-06-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_serviceevent_events_serv_scope_t_edf623_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='ministry_context',
        ),
    ]
