# Generated by Django 5.2.17 on 2026-08-18 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_serviceevent_ministry_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEventPlannerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Operational, non-sensitive coordination notes only. Do not store pastoral, medical, financial, or other private information.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_assignments', to='events.serviceevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_event_planner_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Event Planner / Coordinator',
                'verbose_name_plural': 'Service Event Planners / Coordinators',
                'ordering': ['service_event__start_datetime', 'user__username', 'id'],
                'indexes': [models.Index(fields=['service_event', 'is_active'], name='events_serv_service_1728cc_idx'), models.Index(fields=['user', 'is_active'], name='events_serv_user_id_7b9b2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_event', 'user'), name='unique_service_event_planner_user')],
            },
        ),
    ]
