# Generated by Django 5.2.17 on 2026-08-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_serviceeventplannerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='scheduling_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
