# Generated by Django 5.2.17 on 2026-08-27 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_serviceevent_scheduling_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='service_profile_key',
            field=models.CharField(blank=True, default='', help_text='Stable integration/profile key for this exact service event. It does not control audience, location, recurrence, serving, or permissions.', max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_service_profile_key', message='Use only lowercase ASCII letters, digits, underscores, hyphens, and periods.', regex='^[a-z0-9_.-]+$')]),
        ),
    ]
