# Generated by Django 5.2.17 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_serviceevent_service_profile_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, default="", max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sunday_service", "Sunday Service"),
                            ("bible_study", "Bible Study"),
                            ("special_meeting", "Special Meeting"),
                            ("conference", "Conference"),
                            ("gospel_music", "Gospel Music Night"),
                            ("baptism", "Baptism"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="serviceevent",
            name="service_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_events",
                to="events.serviceprofile",
            ),
        ),
    ]
