# Generated by Django 5.2.17 on 2026-09-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_serviceprofile_serviceevent_service_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='service_profile_key',
        ),
    ]
