# Generated by Django 5.2.14 on 2026-05-22 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('email_alias', models.CharField(blank=True, default='', max_length=180)),
                ('playbook_link', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='ministry_mi_is_acti_121f47_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('member', 'Member'), ('lead', 'Lead'), ('coordinator', 'Coordinator')], default='member', max_length=32)),
                ('skill_level', models.CharField(blank=True, default='', max_length=80)),
                ('can_lead', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ministry.ministryteam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team', 'role', 'display_name'],
                'indexes': [models.Index(fields=['team'], name='ministry_te_team_id_f8e25f_idx'), models.Index(fields=['user'], name='ministry_te_user_id_e90895_idx'), models.Index(fields=['is_active'], name='ministry_te_is_acti_427258_idx'), models.Index(fields=['role'], name='ministry_te_role_72cf5b_idx')],
            },
        ),
    ]
