# Generated by Django 5.2.14 on 2026-05-22 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('ministry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('prepared', 'Prepared'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_assignments', to=settings.AUTH_USER_MODEL)),
                ('ministry_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ministry.ministryteam')),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='events.serviceevent')),
            ],
            options={
                'ordering': ['service_event__start_datetime', 'ministry_team__name'],
            },
        ),
        migrations.CreateModel(
            name='TeamAssignmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_members', to='ministry.teamassignment')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_memberships', to='ministry.teammembership')),
            ],
            options={
                'ordering': ['assignment', 'membership__display_name'],
            },
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='assignments', through='ministry.TeamAssignmentMember', to='ministry.teammembership'),
        ),
        migrations.AddConstraint(
            model_name='teamassignmentmember',
            constraint=models.UniqueConstraint(fields=('assignment', 'membership'), name='unique_team_assignment_member'),
        ),
        migrations.AddIndex(
            model_name='teamassignment',
            index=models.Index(fields=['status'], name='ministry_te_status_d40905_idx'),
        ),
        migrations.AddIndex(
            model_name='teamassignment',
            index=models.Index(fields=['ministry_team'], name='ministry_te_ministr_91f37c_idx'),
        ),
        migrations.AddIndex(
            model_name='teamassignment',
            index=models.Index(fields=['service_event'], name='ministry_te_service_72b7c6_idx'),
        ),
    ]
