# Generated by Django 5.2.15 on 2026-06-28 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_churchstructureunitmemberrecord'),
        ('ministry', '0002_teamassignment_teamassignmentmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryTeamRoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MinistryTeamRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile__sort_order', 'sort_order', 'role_type__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MinistryTeamRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='ministryteam',
            name='is_assignable',
            field=models.BooleanField(default=True, help_text='Whether this team may be selected as a TeamAssignment target. Stored in MINISTRY-STRUCTURE.1B; enforcement is a later slice and does not change current assignment behavior.'),
        ),
        migrations.AddField(
            model_name='ministryteam',
            name='team_kind',
            field=models.CharField(choices=[('ministry_area', 'Ministry Area'), ('department', 'Department'), ('team', 'Team'), ('subteam', 'Subteam'), ('project_group', 'Project Group'), ('custom', 'Custom')], default='team', help_text='Descriptive ministry-structure taxonomy for display/grouping only. Does not gate assignment, membership, visibility, or permissions.', max_length=32),
        ),
        migrations.CreateModel(
            name='MinistryTeamParentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='ministry.ministryteam')),
                ('parent_church_unit', models.ForeignKey(blank=True, help_text='Display anchor only. Does not grant church membership, audience visibility, serving, delegated management, or any permission.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ministry_team_parent_links', to='accounts.churchstructureunit')),
                ('parent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_links', to='ministry.ministryteam')),
            ],
            options={
                'ordering': ['child_team', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MinistryTeamRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational/non-sensitive notes only. Do not store counseling, pastoral, medical, financial, or private information.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='ministry.ministryteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_team_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team', 'role_type__sort_order', 'user__username', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ministryteam',
            name='role_profile',
            field=models.ForeignKey(blank=True, help_text='Explicit ministry role profile for setup/readiness only. Not computed from hierarchy and does not grant membership, serving, or permissions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='ministry.ministryteamroleprofile'),
        ),
        migrations.AddIndex(
            model_name='ministryteam',
            index=models.Index(fields=['team_kind'], name='ministry_mi_team_ki_fc836c_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryteam',
            index=models.Index(fields=['is_assignable'], name='ministry_mi_is_assi_df4e2c_idx'),
        ),
        migrations.AddField(
            model_name='ministryteamrolerequirement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='ministry.ministryteamroleprofile'),
        ),
        migrations.AddField(
            model_name='ministryteamrolerequirement',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_requirements', to='ministry.ministryteamroletype'),
        ),
        migrations.AddField(
            model_name='ministryteamroleassignment',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_assignments', to='ministry.ministryteamroletype'),
        ),
        migrations.AddIndex(
            model_name='ministryteamparentlink',
            index=models.Index(fields=['child_team', 'is_active'], name='ministry_mi_child_t_5208aa_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryteamparentlink',
            index=models.Index(fields=['parent_team', 'is_active'], name='ministry_mi_parent__e23b43_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryteamparentlink',
            index=models.Index(fields=['parent_church_unit', 'is_active'], name='ministry_mi_parent__c44bba_idx'),
        ),
        migrations.AddConstraint(
            model_name='ministryteamparentlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent_church_unit__isnull', True), ('parent_team__isnull', False)), models.Q(('parent_church_unit__isnull', False), ('parent_team__isnull', True)), _connector='OR'), name='ministry_parent_link_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='ministryteamrolerequirement',
            constraint=models.UniqueConstraint(fields=('profile', 'role_type'), name='unique_ministry_team_role_requirement'),
        ),
        migrations.AddIndex(
            model_name='ministryteamroleassignment',
            index=models.Index(fields=['team', 'is_active'], name='ministry_mi_team_id_e3b6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryteamroleassignment',
            index=models.Index(fields=['role_type', 'is_active'], name='ministry_mi_role_ty_329a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryteamroleassignment',
            index=models.Index(fields=['user', 'is_active'], name='ministry_mi_user_id_136a47_idx'),
        ),
    ]
