# Generated by Django 5.2.17 on 2026-08-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_ministryteamroleprofile_ministryteamrolerequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministryteam',
            name='is_worship_rotation_pool',
            field=models.BooleanField(default=False, help_text='Marks this non-assignable ministry container as a Worship rotation pool whose descendants may later be selected for Sunday Worship. This setting schedules nobody and grants no permission.'),
        ),
    ]
