# Generated by Django 5.2.17 on 2026-09-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0004_ministryteam_is_worship_rotation_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamassignment',
            name='reviewed_worship_context_fingerprint',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
