# Generated by Django 5.2.17 on 2026-09-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_serviceprofile_serviceevent_service_profile"),
        ("ministry", "0006_ministryteam_team_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProfileMinistryRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ministry_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_profile_requirement_links",
                        to="ministry.ministryteam",
                    ),
                ),
                (
                    "service_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_requirements",
                        to="events.serviceprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service_profile", "ministry_team"),
                        name="unique_service_profile_ministry_requirement",
                    )
                ],
            },
        ),
    ]
