---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rsnwvvl103hc/app_read/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp

    - /bin/rm -rf $DEPLOYPATH/accounts
    - /bin/rm -rf $DEPLOYPATH/comments
    - /bin/rm -rf $DEPLOYPATH/config
    - /bin/rm -rf $DEPLOYPATH/data
    - /bin/rm -rf $DEPLOYPATH/docs
    - /bin/rm -rf $DEPLOYPATH/reading
    - /bin/rm -rf $DEPLOYPATH/scripts
    - /bin/rm -rf $DEPLOYPATH/static
    - /bin/rm -rf $DEPLOYPATH/templates

    - /bin/cp -R accounts $DEPLOYPATH
    - /bin/cp -R comments $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R reading $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH

    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp run_migrate_godaddy.py $DEPLOYPATH
    - /bin/cp run_collectstatic_godaddy.py $DEPLOYPATH
    - /bin/cp run_create_admin_godaddy.py $DEPLOYPATH
    - /bin/cp run_import_legacy_godaddy.py $DEPLOYPATH

    - /bin/touch $DEPLOYPATH/tmp/restart.txt