# Generated by Django 5.2.14 on 2026-05-15 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_must_change_password'),
        ('comments', '0001_initial'),
        ('reading', '0004_readingplan_description_en_readingplan_name_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectioncomment',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_comments', to='reading.activeplan'),
        ),
        migrations.AddField(
            model_name='reflectioncomment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reflectioncomment',
            name='scripture_display_en',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='reflectioncomment',
            name='scripture_display_zh',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='reflectioncomment',
            name='scripture_ref_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='reflectioncomment',
            name='small_group_at_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_comments', to='accounts.smallgroup'),
        ),
        migrations.AddField(
            model_name='reflectioncomment',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'My Small Group'), ('church', 'Reflection Wall')], db_index=True, default='group', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reflectioncomment',
            index=models.Index(fields=['active_plan', 'plan_day', 'scripture_ref_key'], name='comments_re_active__39e4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectioncomment',
            index=models.Index(fields=['scripture_ref_key', 'visibility'], name='comments_re_scriptu_5ad916_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectioncomment',
            index=models.Index(fields=['user', 'scripture_ref_key'], name='comments_re_user_id_54ab62_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectioncomment',
            index=models.Index(fields=['small_group_at_post', 'scripture_ref_key'], name='comments_re_small_g_942a09_idx'),
        ),
    ]
