# Generated by Django 5.2.14 on 2026-05-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_reflectioncomment_hidden_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflectioncomment',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'My Small Group'), ('church', 'Reflection Wall')], db_index=True, default='group', max_length=20),
        ),
    ]
