# Generated by Django 5.2.15 on 2026-06-13 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_churchstructuremembership'),
        ('comments', '0004_alter_reflectioncomment_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectioncomment',
            name='structure_unit_at_post',
            field=models.ForeignKey(blank=True, help_text='Additive structure snapshot for future privacy migration. Write-only during CS-CORE.4D; current visibility still uses small_group_at_post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_comments_at_post', to='accounts.churchstructureunit'),
        ),
    ]
