# Generated by Django 5.2.15 on 2026-06-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_churchstructuremembership'),
        ('comments', '0005_reflectioncomment_structure_unit_at_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflectioncomment',
            name='structure_unit_at_post',
            field=models.ForeignKey(blank=True, help_text="Structure snapshot driving group reflection visibility since CS-CORE.4G.2: ordinary group read visibility matches this snapshot unit against the viewer's active primary ChurchStructureMembership. small_group_at_post remains legacy compatibility / staff-display / write-path data.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_comments_at_post', to='accounts.churchstructureunit'),
        ),
    ]
