# Generated by Django 5.2.15 on 2026-06-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_churchroleassignment_district_and_more'),
        ('comments', '0006_alter_reflectioncomment_structure_unit_at_post'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reflectioncomment',
            name='comments_re_small_g_942a09_idx',
        ),
        migrations.RemoveField(
            model_name='reflectioncomment',
            name='small_group_at_post',
        ),
        migrations.AlterField(
            model_name='reflectioncomment',
            name='structure_unit_at_post',
            field=models.ForeignKey(blank=True, help_text="Structure snapshot driving group reflection visibility since CS-CORE.4G.2: ordinary group read visibility matches this snapshot unit against the viewer's active primary ChurchStructureMembership. This is the canonical structure-native group snapshot; the legacy small_group_at_post mirror was removed in REFLECTION-MIRROR.1H.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_comments_at_post', to='accounts.churchstructureunit'),
        ),
    ]
