# Generated by Django 5.2.14 on 2026-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('zh', '中文'), ('en', 'English')], default='zh', max_length=2),
        ),
    ]
