# Generated by Django 5.2.14 on 2026-06-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ministrycontext_district_ministry_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchStructureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('root', 'Root'), ('ministry_context', 'Ministry Context'), ('district', 'District'), ('small_group', 'Small Group'), ('fellowship', 'Fellowship'), ('department', 'Department'), ('custom', 'Custom')], max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.churchstructureunit')),
            ],
            options={
                'ordering': ['parent_id', 'sort_order', 'code', 'name'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'code'), name='unique_church_structure_unit_parent_code')],
            },
        ),
    ]
