# Generated by Django 5.2.14 on 2026-06-03 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_churchstructureunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Optional bridge to the future ChurchStructureUnit tree. Not required and does not change current runtime behavior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_districts', to='accounts.churchstructureunit'),
        ),
        migrations.AddField(
            model_name='ministrycontext',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Optional bridge to the future ChurchStructureUnit tree. Not required and does not change current runtime behavior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_ministry_contexts', to='accounts.churchstructureunit'),
        ),
        migrations.AddField(
            model_name='smallgroup',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Optional bridge to the future ChurchStructureUnit tree. Not required and does not change current runtime behavior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_small_groups', to='accounts.churchstructureunit'),
        ),
    ]
