# Generated by Django 5.2.14 on 2026-06-03 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_district_church_structure_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchStructureMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('member', 'Member'), ('visitor', 'Visitor'), ('regular_attendee', 'Regular Attendee'), ('small_group_member', 'Small Group Member')], default='small_group_member', max_length=32)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational/non-sensitive notes only. Do not store counseling, pastoral, medical, financial, or private information.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_church_structure_memberships', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_church_structure_memberships', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.churchstructureunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_structure_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', '-is_primary', 'status', 'start_date', 'id'],
            },
        ),
    ]
