# Generated by Django 5.2.15 on 2026-06-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_churchstructuremembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchroleassignment',
            name='structure_unit',
            field=models.ForeignKey(blank=True, help_text='Canonical future role scope (CS-CORE.2D-A). Optional during the migration: global roles leave this null, and the legacy district / small_group fields remain compatibility scope fields until the group-progress permission switch. Additive only; it does not change role behavior in this slice.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='accounts.churchstructureunit'),
        ),
    ]
