# Generated by Django 5.2.15 on 2026-06-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_churchroleassignment_structure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchroleassignment',
            name='structure_unit',
            field=models.ForeignKey(blank=True, help_text='Canonical structure scope for non-global role assignments. Leave blank for global roles. District/small-group scoped roles require an explicit active ChurchStructureUnit; legacy district / small_group fields are compatibility/admin/display/audit/backfill/rollback context only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='accounts.churchstructureunit'),
        ),
        migrations.AlterField(
            model_name='district',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Legacy-to-structure bridge for setup diagnostics and compatibility. May affect Bible Study structure-audience resolution/generation and generated legacy SmallGroup meetings; does not directly edit memberships, audience rows, serving assignments, permissions, or ServiceEvent audience matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_districts', to='accounts.churchstructureunit'),
        ),
        migrations.AlterField(
            model_name='ministrycontext',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Legacy-to-structure bridge for setup diagnostics and compatibility. May affect Bible Study structure-audience resolution/generation; does not directly edit memberships, audience rows, serving assignments, permissions, or ServiceEvent audience matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_ministry_contexts', to='accounts.churchstructureunit'),
        ),
        migrations.AlterField(
            model_name='smallgroup',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Legacy-to-structure bridge for setup diagnostics and compatibility. May affect Bible Study structure-audience resolution/generation and generated legacy SmallGroup meetings; does not directly edit memberships, audience rows, serving assignments, permissions, or ServiceEvent audience matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_small_groups', to='accounts.churchstructureunit'),
        ),
    ]
