# Generated by Django 5.2.15 on 2026-06-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_churchroleassignment_structure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchroleassignment',
            name='district',
        ),
        migrations.RemoveField(
            model_name='churchroleassignment',
            name='small_group',
        ),
        migrations.AlterField(
            model_name='churchroleassignment',
            name='structure_unit',
            field=models.ForeignKey(blank=True, help_text='Canonical structure scope for non-global role assignments. Leave blank for global roles. District/small-group scoped roles require an explicit active ChurchStructureUnit and are the sole runtime source for scoped-role access.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='accounts.churchstructureunit'),
        ),
    ]
