# Generated by Django 5.2.15 on 2026-06-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_churchroleassignment_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='small_group',
        ),
    ]
