# Generated by Django 5.2.15 on 2026-06-23 01:42
#
# LEGACY-PARENT-FK-FIELD-RETIRE.1A removes the now-redundant legacy parent/context
# FK fields ``SmallGroup.district`` and ``District.ministry_context``. These links
# duplicated the canonical ``ChurchStructureUnit.parent`` hierarchy and were no
# longer read by live runtime/admin/display/resolver code after
# LEGACY-OBJECT-ADMIN-FK.1A/1B, SE-EVENT-LEGACY-WARNING-RETIRE.1A, and
# LEGACY-BRIDGE-RESOLVER-NARROW.1A. This does not remove the ``SmallGroup`` /
# ``District`` / ``MinistryContext`` tables or the ``church_structure_unit``
# mapping bridge FKs.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_small_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='ministry_context',
        ),
        migrations.RemoveField(
            model_name='smallgroup',
            name='district',
        ),
    ]
