# Generated by Django 5.2.15 on 2026-06-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_legacy_parent_context_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Legacy-to-structure bridge for setup diagnostics and compatibility. Does not affect normal Bible Study V2 generation or create legacy SmallGroup meetings; does not directly edit memberships, audience rows, serving assignments, permissions, or ServiceEvent audience matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_districts', to='accounts.churchstructureunit'),
        ),
        migrations.AlterField(
            model_name='ministrycontext',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Legacy-to-structure bridge for setup diagnostics and compatibility. Does not affect normal Bible Study V2 generation, memberships, audience rows, serving assignments, permissions, or ServiceEvent audience matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_ministry_contexts', to='accounts.churchstructureunit'),
        ),
        migrations.AlterField(
            model_name='smallgroup',
            name='church_structure_unit',
            field=models.ForeignKey(blank=True, help_text='Legacy-to-structure bridge for setup diagnostics and compatibility. Does not affect normal Bible Study V2 generation or create legacy SmallGroup meetings; does not directly edit memberships, audience rows, serving assignments, permissions, or ServiceEvent audience matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_small_groups', to='accounts.churchstructureunit'),
        ),
    ]
