# Generated by Django 5.2.15 on 2026-06-24 06:40

from django.db import migrations


def guard_no_legacy_structure_rows(apps, schema_editor):
    blockers = []
    for model_name in ("SmallGroup", "District", "MinistryContext"):
        model = apps.get_model("accounts", model_name)
        count = model.objects.count()
        if count:
            blockers.append(f"{model_name}={count}")

    if blockers:
        raise RuntimeError(
            "LEGACY-STRUCTURE-TABLE-RETIRE.1A aborted: legacy structure "
            "object rows still exist. Run the read-only object-row audit and "
            "complete the guarded purge before applying this migration. "
            "Remaining rows: " + ", ".join(blockers)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_district_church_structure_unit_and_more'),
        ('comments', '0007_remove_reflectioncomment_small_group_at_post'),
        ('events', '0008_remove_serviceevent_ministry_context'),
        ('prayers', '0004_remove_prayerrequest_prayers_pra_small_g_c02632_idx_and_more'),
        ('studies', '0012_remove_v1_bible_study_models'),
    ]

    operations = [
        migrations.RunPython(
            guard_no_legacy_structure_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='ministrycontext',
            name='church_structure_unit',
        ),
        migrations.RemoveField(
            model_name='smallgroup',
            name='church_structure_unit',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='MinistryContext',
        ),
        migrations.DeleteModel(
            name='SmallGroup',
        ),
    ]
