# Generated by Django 5.2.15 on 2026-06-26 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_legacy_structure_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchStructureUnitRoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ChurchStructureUnitRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='churchstructureunit',
            name='role_profile',
            field=models.ForeignKey(blank=True, help_text='Explicit coworker-role profile for setup/readiness. This is not computed from leaf-node status and does not grant membership, permissions, or serving assignments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='accounts.churchstructureunitroleprofile'),
        ),
        migrations.CreateModel(
            name='ChurchStructureUnitRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='accounts.churchstructureunitroleprofile')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_requirements', to='accounts.churchstructureunitroletype')),
            ],
            options={
                'ordering': ['profile__sort_order', 'sort_order', 'role_type__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'role_type'), name='unique_structure_unit_role_requirement')],
            },
        ),
        migrations.CreateModel(
            name='ChurchStructureUnitRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational/non-sensitive notes only. Do not store counseling, pastoral, medical, financial, or private information.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coworker_role_assignments', to='accounts.churchstructureunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_unit_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_assignments', to='accounts.churchstructureunitroletype')),
            ],
            options={
                'ordering': ['unit', 'role_type__sort_order', 'user__username', 'id'],
                'indexes': [models.Index(fields=['unit', 'is_active'], name='accounts_ch_unit_id_cb334f_idx'), models.Index(fields=['role_type', 'is_active'], name='accounts_ch_role_ty_f1dbb0_idx'), models.Index(fields=['user', 'is_active'], name='accounts_ch_user_id_5821ed_idx')],
            },
        ),
    ]
