# Generated by Django 5.2.15 on 2026-06-27 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_churchstructureunitroleprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faith_statement_status', models.CharField(choices=[('unknown', 'Unknown'), ('not_started', 'Not started'), ('sent_pending_signature', 'Sent, pending signature'), ('signed', 'Signed'), ('waived', 'Waived'), ('declined', 'Declined'), ('not_required', 'Not required')], default='unknown', help_text='Faith Statement / 信仰宣言 acceptance-and-signature state. This is specifically the Faith Statement status, not a generic spiritual status, and not course/training progress.', max_length=32)),
                ('faith_statement_signed_date', models.DateField(blank=True, null=True)),
                ('baptism_status', models.CharField(choices=[('unknown', 'Unknown'), ('not_baptized', 'Not baptized'), ('baptized', 'Baptized'), ('recognized', 'Recognized (baptized elsewhere)'), ('waived', 'Waived'), ('not_required', 'Not required')], default='unknown', max_length=32)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Operational membership notes only. Do not store counseling, medical, financial, immigration, or highly sensitive pastoral details.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_member_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_church_member_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='church_member_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'id'],
            },
        ),
    ]
