# Generated by Django 5.2.15 on 2026-06-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_churchmemberrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServingReadinessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable lower-case identifier, e.g. svca_default_formal_serving.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='When set, this policy is the default the evaluator resolves when no explicit policy is passed. At most one active default is allowed.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Serving readiness policies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ServingReadinessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('faith_statement', 'Faith Statement'), ('baptism', 'Baptism')], help_text='Supported V1 fact sources: faith_statement and baptism, both read from ChurchMemberRecord. Course/training requirement types are not supported by the V1 evaluator.', max_length=32)),
                ('accepted_statuses', models.CharField(help_text="Comma-separated member-record status codes that satisfy this requirement, validated against the requirement type's choices.", max_length=255)),
                ('severity', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended')], default='required', help_text='required severity affects is_ready; recommended is warning-only. Even required requirements are warning-only at assignment surfaces in V1.', max_length=16)),
                ('label', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('message_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='accounts.servingreadinesspolicy')),
            ],
            options={
                'ordering': ['policy__sort_order', 'sort_order', 'id'],
            },
        ),
    ]
