# Generated by Django 5.2.15 on 2026-06-28 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_servingreadinesspolicy_servingreadinessrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchStructureUnitMemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_state', models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('unstable_attendee', 'Unstable attendee'), ('inactive', 'Inactive'), ('no_longer_comes', 'No longer comes'), ('graduated', 'Graduated'), ('moved', 'Moved'), ('visitor', 'Visitor'), ('other', 'Other')], default='unknown', help_text='Unit-local attendance/care state. This is operational unit data, not belonging (ChurchStructureMembership), not a global member fact, and not serving eligibility.', max_length=32)),
                ('joined_unit_date', models.DateField(blank=True, null=True)),
                ('group_notes', models.TextField(blank=True, help_text='Unit-local operational notes only. Do not store counseling, medical, financial, immigration, or highly sensitive pastoral details unless a later privacy policy explicitly allows it.')),
                ('care_followup_notes', models.TextField(blank=True, help_text='Restricted care/follow-up notes. Treat as sensitive. Do not expose to ordinary members or delegated leads until a privacy/permission slice explicitly approves access.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_records', to='accounts.churchstructureunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_structure_unit_member_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_unit_member_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit', 'user__username', 'id'],
                'indexes': [models.Index(fields=['unit', 'attendance_state'], name='accounts_ch_unit_id_f228cf_idx'), models.Index(fields=['user'], name='accounts_ch_user_id_e6a34e_idx')],
                'constraints': [models.UniqueConstraint(fields=('unit', 'user'), name='unique_church_structure_unit_member_record')],
            },
        ),
    ]
