# Generated by Django 5.2.17 on 2026-08-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_churchstructureunitmemberrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchstructureunit',
            name='unit_type',
            field=models.CharField(choices=[('root', 'Root'), ('campus', 'Campus / Site'), ('ministry_context', 'Ministry Context'), ('district', 'District'), ('small_group', 'Small Group'), ('fellowship', 'Fellowship'), ('department', 'Department'), ('custom', 'Custom')], max_length=32),
        ),
    ]
