# Generated by Django 5.2.14 on 2026-05-12 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name_zh', models.CharField(max_length=80)),
                ('name_en', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=150)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_runs', to='reading.readingplan')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('reading_text', models.TextField()),
                ('memory_verse', models.CharField(blank=True, max_length=120)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='reading.readingplan')),
            ],
            options={
                'ordering': ['plan', 'day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='BibleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='reading.biblebook')),
            ],
            options={
                'ordering': ['book__order', 'chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='PlanEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('active_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='reading.activeplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'active_plan'), name='unique_user_active_plan_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='reading.readingplanday')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'plan_day'), name='unique_user_plan_day_checkin')],
            },
        ),
    ]
