# Generated by Django 5.2.14 on 2026-05-12 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkin',
            name='unique_user_plan_day_checkin',
        ),
        migrations.AddField(
            model_name='checkin',
            name='active_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='reading.activeplan'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('user', 'active_plan', 'plan_day'), name='unique_user_active_plan_day_checkin'),
        ),
    ]
