# Generated by Django 5.2.14 on 2026-05-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_remove_checkin_unique_user_plan_day_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingplan',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
