# Generated by Django 5.2.14 on 2026-05-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_readingplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
