# Generated by Django 5.2.14 on 2026-05-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_readingplan_description_en_readingplan_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlanDayPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_type', models.CharField(choices=[('reading', 'Reading'), ('memory', 'Memory Verse')], db_index=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField()),
                ('raw_reference', models.CharField(max_length=160)),
                ('scripture_ref_key', models.CharField(db_index=True, max_length=120)),
                ('display_zh', models.CharField(blank=True, default='', max_length=160)),
                ('display_en', models.CharField(blank=True, default='', max_length=160)),
                ('text_url_zh', models.URLField(blank=True, default='', max_length=500)),
                ('text_url_en', models.URLField(blank=True, default='', max_length=500)),
                ('audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_passages', to='reading.readingplanday')),
            ],
            options={
                'ordering': ['plan_day', 'passage_type', 'sort_order'],
                'indexes': [models.Index(fields=['plan_day', 'passage_type'], name='reading_rea_plan_da_32309c_idx'), models.Index(fields=['scripture_ref_key'], name='reading_rea_scriptu_aeb139_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan_day', 'passage_type', 'sort_order'), name='unique_plan_day_passage_order')],
            },
        ),
    ]
