# Generated by Django 5.2.14 on 2026-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_readingplandaypassage'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='introduction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='introduction_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='pastoral_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='pastoral_note_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='reading_guidance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='reading_guidance_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
