# Generated by Django 5.2.14 on 2026-05-21 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_readingplan_introduction_readingplan_introduction_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGuidePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, default='', max_length=160)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True, default='')),
                ('guide_type', models.CharField(choices=[('general', 'General'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='general', max_length=20)),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
                ('day_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_posts', to='reading.activeplan')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_guide_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
    ]
