# Generated by Django 5.2.15 on 2026-07-04 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_churchstructureunitmemberrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, default='', max_length=180)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important')], default='normal', max_length=16)),
                ('publish_start', models.DateTimeField()),
                ('publish_end', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Official Announcement',
                'verbose_name_plural': 'Official Announcements',
                'ordering': ['-publish_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAudienceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_scope_links', to='announcements.announcement')),
                ('structure_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_audience_scopes', to='accounts.churchstructureunit')),
            ],
            options={
                'verbose_name': 'Announcement Audience Scope',
                'verbose_name_plural': 'Announcement Audience Scopes',
                'ordering': ['announcement__publish_start', 'structure_unit__parent_id', 'structure_unit__sort_order', 'structure_unit__code', 'structure_unit__name'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status'], name='announcemen_status_d67968_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publish_start'], name='announcemen_publish_39df62_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publish_end'], name='announcemen_publish_206bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementaudiencescope',
            index=models.Index(fields=['announcement'], name='announcemen_announc_40d973_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementaudiencescope',
            index=models.Index(fields=['structure_unit'], name='announcemen_structu_38d4aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudiencescope',
            constraint=models.UniqueConstraint(fields=('announcement', 'structure_unit'), name='unique_announcement_audience_scope'),
        ),
    ]
