# Generated by Django 5.2.14 on 2026-05-20 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=3000)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('group', 'My Small Group'), ('church', 'Prayer Wall')], db_index=True, default='group', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('answer_note', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('small_group_at_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='accounts.smallgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_marks', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_marks', to='prayers.prayerrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_comments', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prayers.prayerrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['visibility', 'status'], name='prayers_pra_visibil_b16143_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['user', 'status'], name='prayers_pra_user_id_3ba07c_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['small_group_at_post', 'status'], name='prayers_pra_small_g_c02632_idx'),
        ),
        migrations.AddConstraint(
            model_name='prayermark',
            constraint=models.UniqueConstraint(fields=('prayer_request', 'user'), name='unique_prayer_mark_per_user'),
        ),
    ]
