# Generated by Django 5.2.15 on 2026-06-18 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_prayer_structure_snapshots(apps, schema_editor):
    PrayerRequest = apps.get_model("prayers", "PrayerRequest")

    safe_group_prayers = PrayerRequest.objects.filter(
        visibility="group",
        small_group_at_post__isnull=False,
        small_group_at_post__church_structure_unit__isnull=False,
        small_group_at_post__church_structure_unit__is_active=True,
        small_group_at_post__church_structure_unit__unit_type="small_group",
    ).select_related("small_group_at_post__church_structure_unit")

    for prayer in safe_group_prayers.iterator():
        prayer.structure_unit_at_post_id = (
            prayer.small_group_at_post.church_structure_unit_id
        )
        prayer.save(update_fields=["structure_unit_at_post"])


def reverse_prayer_structure_snapshot_backfill(apps, schema_editor):
    # The schema rollback drops the field; no legacy mirror data is changed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_churchroleassignment_structure_unit'),
        ('prayers', '0002_prayerrequest_hidden_at_prayerrequest_hidden_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='structure_unit_at_post',
            field=models.ForeignKey(blank=True, help_text='Structure-native snapshot driving group prayer visibility. small_group_at_post remains a legacy compatibility / display / history mirror.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests_at_post', to='accounts.churchstructureunit'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['structure_unit_at_post', 'status'], name='prayers_pra_structu_ad18dd_idx'),
        ),
        migrations.RunPython(
            backfill_prayer_structure_snapshots,
            reverse_prayer_structure_snapshot_backfill,
        ),
    ]
