# Generated by Django 5.2.15 on 2026-06-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_churchroleassignment_structure_unit_and_more'),
        ('prayers', '0003_prayerrequest_structure_unit_at_post_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prayerrequest',
            name='prayers_pra_small_g_c02632_idx',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='small_group_at_post',
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='structure_unit_at_post',
            field=models.ForeignKey(blank=True, help_text='Structure-native snapshot driving group prayer visibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests_at_post', to='accounts.churchstructureunit'),
        ),
    ]
