# Generated by Django 5.2.14 on 2026-05-21 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_district_churchroleassignment_smallgroup_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, default='', max_length=180)),
                ('scripture_reference', models.CharField(blank=True, default='', max_length=180)),
                ('prestudy_datetime', models.DateTimeField(blank=True, null=True)),
                ('study_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=180)),
                ('meeting_link', models.URLField(blank=True, default='', max_length=500)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('district', 'District'), ('small_group', 'Small Group')], default='global', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bible_study_sessions', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_sessions', to='accounts.district')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='studies.biblestudyseries')),
                ('small_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_sessions', to='accounts.smallgroup')),
            ],
            options={
                'ordering': ['-study_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_body', models.TextField(blank=True, default='')),
                ('guide_body_en', models.TextField(blank=True, default='')),
                ('discussion_questions', models.TextField(blank=True, default='')),
                ('discussion_questions_en', models.TextField(blank=True, default='')),
                ('prestudy_notes', models.TextField(blank=True, default='')),
                ('prestudy_notes_en', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='studies.biblestudysession')),
            ],
        ),
    ]
