# Generated by Django 5.2.14 on 2026-05-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyWorshipSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, default='', max_length=160)),
                ('song_key', models.CharField(blank=True, default='', max_length=40)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('chord_url', models.URLField(blank=True, default='', max_length=500)),
                ('lyrics_url', models.URLField(blank=True, default='', max_length=500)),
                ('note', models.TextField(blank=True, default='')),
                ('note_en', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worship_songs', to='studies.biblestudysession')),
            ],
            options={
                'ordering': ['session', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sort_order'), name='unique_bible_study_worship_song_order')],
            },
        ),
    ]
