# Generated by Django 5.2.14 on 2026-05-26 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_district_churchroleassignment_smallgroup_district'),
        ('events', '0001_initial'),
        ('studies', '0002_biblestudyworshipsong'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, default='', max_length=180)),
                ('scripture_reference', models.CharField(blank=True, default='', max_length=180)),
                ('lesson_date', models.DateField()),
                ('prestudy_datetime', models.DateTimeField(blank=True, null=True)),
                ('pastor_guide_body', models.TextField(blank=True, default='')),
                ('pastor_guide_body_en', models.TextField(blank=True, default='')),
                ('global_discussion_questions', models.TextField(blank=True, default='')),
                ('global_discussion_questions_en', models.TextField(blank=True, default='')),
                ('prestudy_notes', models.TextField(blank=True, default='')),
                ('prestudy_notes_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bible_study_lessons', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='studies.biblestudyseries')),
            ],
            options={
                'ordering': ['-lesson_date', '-prestudy_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=180)),
                ('location_en', models.CharField(blank=True, default='', max_length=180)),
                ('meeting_link', models.URLField(blank=True, default='', max_length=500)),
                ('discussion_leader_name', models.CharField(blank=True, default='', max_length=160)),
                ('group_direction', models.TextField(blank=True, default='')),
                ('group_direction_en', models.TextField(blank=True, default='')),
                ('group_questions', models.TextField(blank=True, default='')),
                ('group_questions_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bible_study_meetings', to=settings.AUTH_USER_MODEL)),
                ('discussion_leader_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_discussion_meetings', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='studies.biblestudylesson')),
                ('service_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_meetings', to='events.serviceevent')),
                ('small_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_study_meetings', to='accounts.smallgroup')),
            ],
            options={
                'ordering': ['-meeting_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyMeetingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('discussion_leader', 'Discussion Leader'), ('worship_lead', 'Worship Lead'), ('pianist', 'Pianist'), ('support', 'Support'), ('host', 'Host')], max_length=40)),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('notes_en', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='studies.biblestudymeeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_meeting_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', 'role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyMeetingWorshipSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, default='', max_length=160)),
                ('song_key', models.CharField(blank=True, default='', max_length=40)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('chord_url', models.URLField(blank=True, default='', max_length=500)),
                ('lyrics_url', models.URLField(blank=True, default='', max_length=500)),
                ('arrangement_notes', models.TextField(blank=True, default='')),
                ('arrangement_notes_en', models.TextField(blank=True, default='')),
                ('worship_lead_name', models.CharField(blank=True, default='', max_length=160)),
                ('support_notes', models.TextField(blank=True, default='')),
                ('support_notes_en', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worship_songs', to='studies.biblestudymeeting')),
                ('worship_lead_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_worship_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='biblestudymeeting',
            constraint=models.UniqueConstraint(fields=('lesson', 'small_group'), name='unique_bible_study_meeting_lesson_group'),
        ),
        migrations.AddConstraint(
            model_name='biblestudymeetingworshipsong',
            constraint=models.UniqueConstraint(fields=('meeting', 'sort_order'), name='unique_bible_study_meeting_song_order'),
        ),
    ]
