# Generated by Django 5.2.14 on 2026-05-27 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_district_churchroleassignment_smallgroup_district'),
        ('studies', '0004_biblestudyseries_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudyseries',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_schedules', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='biblestudyseries',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('district', 'District'), ('small_group', 'Small Group')], default='global', max_length=32),
        ),
        migrations.AddField(
            model_name='biblestudyseries',
            name='small_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_schedules', to='accounts.smallgroup'),
        ),
    ]
