# Generated by Django 5.2.14 on 2026-05-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ministrycontext_district_ministry_context'),
        ('studies', '0005_biblestudyseries_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudyseries',
            name='ministry_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_series', to='accounts.ministrycontext'),
        ),
        migrations.AlterField(
            model_name='biblestudyseries',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('ministry_context', 'Ministry Context'), ('district', 'District'), ('small_group', 'Small Group')], default='global', max_length=32),
        ),
    ]
