# Generated by Django 5.2.14 on 2026-06-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_churchstructuremembership'),
        ('studies', '0006_biblestudyseries_ministry_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudySeriesAudienceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_scope_links', to='studies.biblestudyseries')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bible_study_series_audience_scopes', to='accounts.churchstructureunit')),
            ],
            options={
                'ordering': ['series__title', 'unit__parent_id', 'unit__sort_order', 'unit__code', 'unit__name'],
                'indexes': [models.Index(fields=['series'], name='studies_bib_series__3a2328_idx'), models.Index(fields=['unit'], name='studies_bib_unit_id_b97836_idx')],
                'constraints': [models.UniqueConstraint(fields=('series', 'unit'), name='unique_bible_study_series_audience_scope')],
            },
        ),
    ]
