# Generated by Django 5.2.15 on 2026-06-15 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_churchroleassignment_structure_unit'),
        ('events', '0005_serviceeventaudiencescope'),
        ('studies', '0008_backfill_bible_study_series_audience_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyMeetingAudienceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['meeting__meeting_datetime', 'unit__parent_id', 'unit__sort_order', 'unit__code', 'unit__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='biblestudymeeting',
            name='unique_bible_study_meeting_lesson_group',
        ),
        migrations.AddField(
            model_name='biblestudymeeting',
            name='anchor_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchored_bible_study_meetings', to='accounts.churchstructureunit'),
        ),
        migrations.AddField(
            model_name='biblestudymeeting',
            name='generation_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='biblestudymeeting',
            name='meeting_kind',
            field=models.CharField(choices=[('normal', 'Normal group meeting'), ('higher_level', 'Higher-level meeting'), ('joint', 'Multi-unit joint meeting'), ('cancelled_replacement', 'Cancelled / replacement week')], default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='biblestudymeeting',
            name='small_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bible_study_meetings', to='accounts.smallgroup'),
        ),
        migrations.AddConstraint(
            model_name='biblestudymeeting',
            constraint=models.UniqueConstraint(condition=models.Q(('small_group__isnull', False)), fields=('lesson', 'small_group'), name='unique_bible_study_meeting_lesson_group'),
        ),
        migrations.AddConstraint(
            model_name='biblestudymeeting',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_key__isnull', False)), fields=('lesson', 'generation_key'), name='unique_bible_study_meeting_lesson_generation_key'),
        ),
        migrations.AddField(
            model_name='biblestudymeetingaudiencescope',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_scope_links', to='studies.biblestudymeeting'),
        ),
        migrations.AddField(
            model_name='biblestudymeetingaudiencescope',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bible_study_meeting_audience_scopes', to='accounts.churchstructureunit'),
        ),
        migrations.AddIndex(
            model_name='biblestudymeetingaudiencescope',
            index=models.Index(fields=['meeting'], name='studies_bib_meeting_09d20b_idx'),
        ),
        migrations.AddIndex(
            model_name='biblestudymeetingaudiencescope',
            index=models.Index(fields=['unit'], name='studies_bib_unit_id_a070e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='biblestudymeetingaudiencescope',
            constraint=models.UniqueConstraint(fields=('meeting', 'unit'), name='unique_bible_study_meeting_audience_scope'),
        ),
    ]
