# Generated by Django 5.2.15 on 2026-06-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_biblestudymeetingaudiencescope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblestudyseries',
            name='district',
        ),
        migrations.RemoveField(
            model_name='biblestudyseries',
            name='ministry_context',
        ),
        migrations.RemoveField(
            model_name='biblestudyseries',
            name='scope_type',
        ),
        migrations.RemoveField(
            model_name='biblestudyseries',
            name='small_group',
        ),
    ]
