# Generated by Django 5.2.15 on 2026-06-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_remove_biblestudyseries_district_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='biblestudymeeting',
            name='unique_bible_study_meeting_lesson_group',
        ),
        migrations.RemoveField(
            model_name='biblestudymeeting',
            name='small_group',
        ),
    ]
