# Generated by Django 5.2.15 on 2026-06-23 22:37

from django.db import migrations


def abort_if_v1_bible_study_rows_exist(apps, schema_editor):
    """Guard V1 schema removal until target DBs have no V1 rows."""
    guarded_models = (
        ("BibleStudySession", "legacy BibleStudySession rows"),
        ("BibleStudyGuide", "legacy BibleStudyGuide child rows"),
        ("BibleStudyWorshipSong", "legacy BibleStudyWorshipSong child rows"),
    )
    blockers = []
    for model_name, label in guarded_models:
        model = apps.get_model("studies", model_name)
        count = model.objects.count()
        if count:
            blockers.append(f"{label}: {count}")

    if blockers:
        raise RuntimeError(
            "BS-V1-SCHEMA-RETIRE.1A blocked: V1 Bible Study rows still exist. "
            "Run the approved V1 purge preflight/cleanup on the target DB before "
            "applying this schema-removal migration. Blockers: "
            + "; ".join(blockers)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_remove_biblestudymeeting_unique_bible_study_meeting_lesson_group_and_more'),
    ]

    operations = [
        migrations.RunPython(
            abort_if_v1_bible_study_rows_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='BibleStudyGuide',
        ),
        migrations.DeleteModel(
            name='BibleStudyWorshipSong',
        ),
        migrations.DeleteModel(
            name='BibleStudySession',
        ),
    ]
