# Generated by Django 5.2.15 on 2026-06-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_remove_v1_bible_study_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudymeetingrole',
            name='confirmation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='biblestudymeetingrole',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
