# Generated by Django 5.2.15 on 2026-07-03 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_churchstructureunitmemberrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('organizer', models.CharField(blank=True, default='', max_length=180)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=180)),
                ('location_en', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_community_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Activity',
                'verbose_name_plural': 'Community Activities',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CommunityActivityAudienceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_scope_links', to='community_events.communityactivity')),
                ('structure_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_activity_audience_scopes', to='accounts.churchstructureunit')),
            ],
            options={
                'ordering': ['activity__start_datetime', 'structure_unit__parent_id', 'structure_unit__sort_order', 'structure_unit__code', 'structure_unit__name'],
            },
        ),
        migrations.AddIndex(
            model_name='communityactivity',
            index=models.Index(fields=['status'], name='community_e_status_563405_idx'),
        ),
        migrations.AddIndex(
            model_name='communityactivity',
            index=models.Index(fields=['start_datetime'], name='community_e_start_d_136fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='communityactivityaudiencescope',
            index=models.Index(fields=['activity'], name='community_e_activit_1d8893_idx'),
        ),
        migrations.AddIndex(
            model_name='communityactivityaudiencescope',
            index=models.Index(fields=['structure_unit'], name='community_e_structu_7bf785_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityactivityaudiencescope',
            constraint=models.UniqueConstraint(fields=('activity', 'structure_unit'), name='unique_community_activity_audience_scope'),
        ),
    ]
