# Generated by Django 5.2.15 on 2026-07-03 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('signed_up', 'Signed up'), ('cancelled', 'Cancelled')], default='signed_up', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='community_events.communityactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activity_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity__start_datetime', 'id'],
                'indexes': [models.Index(fields=['activity', 'status'], name='community_e_activit_8cf8c6_idx'), models.Index(fields=['user', 'status'], name='community_e_user_id_cf58d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_signup_user')],
            },
        ),
    ]
