# Generated by Django 5.2.15 on 2026-07-03 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_events', '0002_activitysignup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivity',
            name='requested_audience_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='communityactivity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='CommunityActivitySubmissionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_community_activity_submission_blocks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activity_submission_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Activity Submission Block',
                'verbose_name_plural': 'Community Activity Submission Blocks',
                'ordering': ['-is_active', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_community_activity_submission_block_user')],
            },
        ),
    ]
