# Generated by Django 5.2.15 on 2026-07-03 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_events', '0004_communityactivity_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivityCoOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_organizer_links', to='community_events.communityactivity')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_community_activity_co_organizer_links', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activity_co_organizer_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Activity Co-organizer',
                'verbose_name_plural': 'Community Activity Co-organizers',
                'ordering': ['activity__start_datetime', 'user__username', 'id'],
                'indexes': [models.Index(fields=['activity'], name='community_e_activit_24896c_idx'), models.Index(fields=['user'], name='community_e_user_id_c6b0b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'user'), name='unique_community_activity_co_organizer')],
            },
        ),
    ]
