# Generated by Django 5.2.15 on 2026-07-04 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_events', '0005_communityactivitycoorganizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivity',
            name='capacity_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
