# Generated by Django 5.2.17 on 2026-08-13 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(max_length=100)),
                ('source_model_label', models.CharField(blank=True, max_length=255)),
                ('source_object_id', models.CharField(blank=True, max_length=255)),
                ('notification_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('target_url', models.CharField(help_text='Internal navigation path only; the destination still enforces its own permissions.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notify_rec_read_created_idx'), models.Index(fields=['source_module', 'source_model_label', 'source_object_id'], name='notify_source_snapshot_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='notifications_unique_recipient_dedupe')],
            },
        ),
    ]
